### ISSUE TITLE
Support for multiple kubernetes clusters

### ISSUE THREAD

**Issue by voki** [DaspawnW/vault-crd#18]
We are using one Vault for multiple kubernetes clusters.
It is configured by passing path argument to vault auth enable command.
```
vault auth enable --path="kube-tst" kubernetes
```
Looks like, it is not supported in vault-crd currently and all requests are always send to /v1/auth/kubernetes/ endpoint.
In this case path is /v1/auth/kube-tst/
It would be nice if we could override "kubernetes" path by providing env variable.

**Comment by DaspawnW** [comment]
Hi @voki,

Sorry I forgot to Document the Pull Request #17 made few days ago. Please have a look, if it doesn't fit your requirements. If you have any questions please feel free to reopen the issue.

Cheers,
Björn

**Comment by voki** [comment]
Hi @DaspawnW , 

That's exactly what I was looking for.
Great job with this crd!
I am looking forward to test it tomorrow :)

Thanks,
Kamil
