### ISSUE TITLE
Dynamic Secrets

### ISSUE THREAD

**Issue by rocktavious** [DaspawnW/vault-crd#19]
Hello - Is there any plans for adding dynamic secret tracking to vault-crd?  We currently use this and are liking the model so far but the fact that its limited to static secrets doesn't allow us to unlock the full potential of vault.  I work for Under Armour and its possible we could dedicate some engineering effort to adding this feature if you are willing to accept an implementation or have ideas on how you'd like it implement.

Thanks!

**Comment by DaspawnW** [comment]
Hi,

sounds very interresting. For now I had no plan to add dynamic secrets, as it wasn't so interesting for us.
I'm completely open if you are interrested to implement this :-)
If you are interrested we can add maybe some of your colleagues also as maintainer to the project?
If there is any interrest we can maybe have a short WebEx session to discuss some points?!

Cheers,
Björn

**Comment by DaspawnW** [comment]
Hi @rocktavious,

please reopen if you still have questions.

BR,
Björn
