### ISSUE TITLE
Add `Auth` to dockercfgsecret

### ISSUE THREAD

**Issue by andrewl3wis** [DaspawnW/vault-crd#20]
Hey, it'd be great if `DOCKERCFGSECRET` was harmonized with the format that is created by kubectl and added an the `auth` field to the secret that is created in k8s, while not necessary for the the secret to work with kubernetes for image pulls, some external tools like Weavework's flux expect it to exist(https://github.com/weaveworks/flux/issues/1596). 

In the `1.13.0` release of `kubectl` they had also stripped out the `auth` field, but then re-added it in https://github.com/kubernetes/kubernetes/pull/72344

**Comment by DaspawnW** [comment]
Release 1.2.3 containing bugfix will be available in few minutes.
