### ISSUE TITLE
Errors on documentation

### ISSUE THREAD

**Issue by Sayrus** [DaspawnW/vault-crd#22]
I couldn't find anywhere to create a merge request for the documentation.

https://vault.koudingspawn.de/install-vault-crd
`base64 -D` should be `base64 -d`

`KUBERNETES_VAULT_PATH` is not described in the documentation but implemented in `/src/main/java/de/koudingspawn/vault/vault/VaultConfiguration.java:62`.
A simple description could be:
```Please specify here the Vault auth path to be used. Defaults to kubernetes.```

**Comment by DaspawnW** [comment]
Hi @Sayrus,

thanks a lot for your feedback. I've updated the documentation, it is a hosted gitbook at gitbook.com, so I don't know if it is possible to send merge requests there.
