### ISSUE TITLE
Support DOCKERCFG in a version 2 KV store

### ISSUE THREAD

**Issue by nealf** [DaspawnW/vault-crd#27]
It appears as though the DOCKERCFG Secret Type does not currently work with a Version 2 KV secret engine in Vault. I had to create a new version 1 KV store in Vault and put Docker credentials in it in order for vault-crd to properly create the `kubernetes.io/dockercfg` secret.

As a quick solution, it would be nice to just [document](https://vault.koudingspawn.de/supported-secret-types/secret-type-dockercfg) that DOCKERCFG requires a v1 secret engine to save others the time of working through this issue. :-)

Thanks for the great project!

**Comment by DaspawnW** [comment]
Hi @nealf,

thnx for the feature request and sorry for my late response.
I've created a new release that contains support for version 2 KV store of Vault: https://github.com/DaspawnW/vault-crd/releases/tag/1.4.0

Cheers,
 Björn
