### ISSUE TITLE
Run multiple vault on same cluster in different namespaces

### ISSUE THREAD

**Issue by harshmanvar** [DaspawnW/vault-crd#43]
Hi There, It's amazing CRD i am using it and working well.

i have a requirement like, want to run this CRD for two vault.

My one vault is in **default** namespace and secret in the **default** namespace.

Now i have set up new vault in **dev** namespace and looking forward to sync secrets in **dev** namespace it is possible with single deployment or i have to do multiple deployments of CRD.

**Comment by DaspawnW** [comment]
Hi @harshmanvar ,

I'm sorry currently this is not supported. I think this requires a change in the structure of vault-crd or an annotation that allows to define something simmilar as used in nginx-ingress to have multiple of them.
I'll think about it, maybe you have a good idea?

**Comment by DaspawnW** [comment]
Hi @harshmanvar ,

I'm sorry currently this is not supported. I think this requires a change in the structure of vault-crd or an annotation that allows to define something simmilar as used in nginx-ingress to have multiple of them.
I'll think about it, maybe you have a good idea?

**Comment by harshmanvar** [comment]
Hi @DaspawnW ,

 Thanks a lot for writing back. i have not much explored and check the structure of **vault-crd** so no good idea as of now syncing multiple vaults. however, i have simply resolved the issue by deploying another **vault-crd** POD in respective namespace.  

will update you if anything there.
 
Thanks a ton..!
