### ISSUE TITLE
[Question] Does creating K8s secrets store them in ETCD

### ISSUE THREAD

**Issue by operatorequals** [DaspawnW/vault-crd#62]
Hello!

I skimmed through the documentation and got that this project creates Kubernetes Secrets from Vault secrets.
Yet, I have not found out if the Kubernetes Secrets created through this process are stored in ETCD or there is some special handling for them.

**Comment by DaspawnW** [comment]
Hi @operatorequals,

Vault-CRD is an operator that acts on the api server. It depends at the end on your api server how it is configured if it will encrypt secrets at rest.
