### ISSUE TITLE
Support for kv backend version 2 

### ISSUE THREAD

**Issue by andrewl3wis** [DaspawnW/vault-crd#7]
I'd love to see support for version 2 of the kv backend, I'd really like to use the versioning functionality that it added.

**Comment by DaspawnW** [comment]
Hi @andrewl3wis,

I'll release an update at the end of the weekend.

Cheers,
 Björn

**Comment by DaspawnW** [comment]
Hi @andrewl3wis,

I've implemented the versioned kv 2 engine support.
If you are upgrading to the new version 1.2.0 please also reapply the custom resource definition.
For more information please see https://vault.koudingspawn.de/supported-secret-types/secret-type-keyvaluev2

Cheers,
 Björn
